### ISSUE TITLE
Testing endpoints

### ISSUE THREAD

**Issue by karthik-NvY** [karthik-NvY/T02-CS305#31]
Submit reports for testing the login-in and sign-up endpoints

**Comment by PavithranGoud** [comment]
Completed testing of login and sign-up endpoints.
![login_endpoints_testing](https://github.com/karthik-NvY/T02-CS305/assets/115581142/5b7be978-ed39-46d7-9ab7-48466c489b10)
![signup_endpoint_testing](https://github.com/karthik-NvY/T02-CS305/assets/115581142/d6f1eeb4-a1cf-4119-8d43-a6e56a7f5175)
