### ISSUE TITLE
Template View page UI/UX

### ISSUE THREAD

**Issue by yashaswinivajja** [karthik-NvY/T02-CS305#80]
This page will contain all the templates you can use, resume editing,…

**Comment by Chaitanya150504** [comment]
https://www.canva.com/design/DAF9pPvDSKc/3iIo08CkwhYfj_MooNZDAQ/edit?utm_content=DAF9pPvDSKc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Template page #80 issue done
